//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class autos
    {
        public int id_auto { get; set; }
        public string placa { get; set; }
        public string modelo { get; set; }
        public int id_marca { get; set; }
        public int cc { get; set; }
        public string color { get; set; }
        [Display(Name = "Fecha de Fabricacion")]
        [DataType(DataType.Date)]
        public System.DateTime fechafab { get; set; }
        public string estado { get; set; }
        public virtual marca marca { get; set; }
        
    }
}
